### ISSUE TITLE
Support additional phantom parameters

### ISSUE THREAD

**Issue by CoderJoeW** [flaminggenius/PhantomGUI#8]
Added support for the following phantom parameters 

Ref: https://github.com/jhead/phantom

Options:
  -6	Optional: Enables IPv6 support on port 19133 (experimental)
  -bind string
    	Optional: IP address to listen on. Defaults to all interfaces. (default "0.0.0.0")
  -bind_port int
    	Optional: Port to listen on. Defaults to 0, which selects a random port.
    	Note that phantom always binds to port 19132 as well, so both ports need to be open.
  -debug
    	Optional: Enables debug logging
  -remove_ports
    	Optional: Forces ports to be excluded from pong packets (experimental)
  -server string
    	Required: Bedrock/MCPE server IP address and port (ex: 1.2.3.4:19132)
  -timeout int
    	Optional: Seconds to wait before cleaning up a disconnected client (default 60)

**Comment by ghost** [comment]
hi flaminggenius. I'd like to work on this item as part of #hacktoberfest. Would you please assign it to me?

**Comment by CoderJoeW** [comment]
done @pdelco

**Comment by ghost** [comment]
hi flaminggenius, would you mind including a label for hacktoberfest-accepted? thanks!

**Comment by CoderJoeW** [comment]
no problem @pdelco
